-- Treesitter auto-start (disabled since treesitter config handles this)
-- vim.api.nvim_create_autocmd('FileType', {
--     pattern = { '<filetype>' },
--     callback = function() vim.treesitter.start() end,
-- })
