hl.on("hyprland.start", function ()
    --hl.exec_cmd("qs -c noctalia-shell")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("flameshot")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swaybg -i ~/Downloads/Wallpapers/alien.png")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("batsignal")
end)

