
strip_trailing_spaces always

copy_on_select yes

url_prefixes http https file ftp gemini git

detect_urls yes 

open_url_with default

window_padding_width 10

single_window_margin_width 0

window_strategy center

resize_debounce_time 0.1

hide_window_decorations yes 

remember_window_size yes 

enable_audio_bell no

visual_bell_duration 0.1

font_family JetBrains Mono 

bold_font auto

italic_font auto 

bold_italic_font auto 

font_size 12.0

modify_font line_height 115%

text_composition_strategy legacy

cursor_shape block

shell_integration no-cursor

cursor_blink_interval 0.5

cursor_stop_blinking_after 25.0

background_opacity 1.0

# cerulean / oceanic theme

background            #0B1E2D
foreground            #E8F3F3
cursor                #D8453A
cursor_text_color     #0B1E2D

selection_background   #1D4560
selection_foreground    #E8F3F3

# black
color0  #16324A
color8  #4C6A7E

# red
color1  #C97064
color9  #E08D80

# green
color2  #7FCDC4
color10 #9CDCD4

# yellow
color3  #E8A87C
color11 #F0BE9C

# blue
color4  #2E86AB
color12 #5FA8C7

# magenta
color5  #8C7CB0
color13 #A69CC4

# cyan
color6  #5FA8C7
color14 #7FCDC4

# white
color7  #B4E4DD
color15 #E8F3F3
