
strip_trailing_spaces always

copy_on_select yes

url_prefixes http https file ftp gemini git

detect_urls yes 

open_url_with default

window_padding_width 0

single_window_margin_width 0

window_strategy center

resize_debounce_time 0.1

hide_window_decorations yes 

remember_window_size yes 

enable_audio_bell no

visual_bell_duration 0.1

font_family JetBrains Mono 

bold_font auto

italic_font auto 

bold_italic_font auto 

font_size 12.0
modify_font line_height 115%
text_composition_strategy legacy

cursor_shape block

shell_integration no-cursor

cursor_blink_interval 0.5

cursor_stop_blinking_after 15.0

background_opacity 0.8


# BEGIN_KITTY_THEME
# Base2Tone Suburb Dark
include current-theme.conf
# END_KITTY_THEME
