;;; fedi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fedi.el

(register-definition-prefixes "fedi" '("fedi-"))


;;; Generated autoloads from fedi-auth.el

(register-definition-prefixes "fedi-auth" '("fedi-auth-"))


;;; Generated autoloads from fedi-http.el

(register-definition-prefixes "fedi-http" '("fedi-"))


;;; Generated autoloads from fedi-iso.el

(register-definition-prefixes "fedi-iso" '("fedi-iso-639-"))


;;; Generated autoloads from fedi-post.el

(register-definition-prefixes "fedi-post" '("fedi-post-"))

;;; End of scraped data

(provide 'fedi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fedi-autoloads.el ends here
