exec-once = waybar
exec-once = swaync
exec-once = swaybg -i /home/tyrone/Downloads/Wallpapers/wallpaper16.png -m fill
exec-once = hypridle
exec-once = flameshot
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

