general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    gaps_workspaces = 0
    # col.active_border =  
    # col.inactive_border = 
    layout = master #master/scrolling/dwindle/monocle
    allow_tearing = false
    resize_on_border = true
}

decoration {
    rounding = 10
    active_opacity = 1.00
    rounding_power = 5.0
    inactive_opacity = 1.00
    fullscreen_opacity = 1.00

    blur {
        enabled = true
        size = 10
        passes = 3 
        ignore_opacity = true
        new_optimizations = true
    }
}

animations = true

monitor =,preferred,auto,1

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5 
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 0.5
    explicit_column_widths = 0.667
    direction = right
}

master {
    allow_small_split = true
    special_scale_factor = 0.5
    mfact = 0.6
    new_status = slave
    new_on_top = true
    orientation = left
}

input {
    kb_layout = us
    kb_variant =
    kb_model = 
    kb_options =
    kb_rules = 

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0
}

gestures {
    workspace_swipe_touch = false
}

#ENVIRONMENT

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland


env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

env = GDK_SCALE,1

env = MOZ_ENABLE_WAYLAND,1

env = XCURSOR_SIZE,24

env = APPIMAGELAUNCHER_DISABLE,0

env = OZONE_PLATFORM,wayland

