
#Disable blue for every window
#windowrule = match:class .*, no_blur on


#Floating

# windowrule = match:class ^(guifetch), float on

windowrule = match:class pavucontrol, center on
windowrule = match:class pavucontrol, float on
windowrule = match:class pavucontrol, size (monitor_w*.45)(monitor_h*.45)

windowrule = match:class org.pulseaudio.pavucontrol, center on
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class org.pulseaudio.pavucontrol, size (monitor_w*.45)(monitor_h*.45)

windowrule = match:class app.zen_browser.zen, float on
windowrule = match:class app.zen_browser.zen, size (monitor_w*.60) (monitor_h*.55)

windowrule = match:class ghostty, center on
windowrule = match:class ghostty, float on
windowrule = match:class ghostty, size (monitor_w*.60) (monitor_h*.45)

windowrule = match:class nemo, float on
windowrule = match:class nemo, size (monitor_w*.60) (monitor_h*.45)

windowrule = match:class nm-connection-editor, float on
windowrule = match:class nm-connection-editor, size (monitor_w*.50) (monitor_h*.50)


windowrule = match:class com.mitchellh.ghostty, float on
windowrule = match:class com.mitchellh.ghostty, size (monitor_w*.70) (monitor_h*.55)

windowrule = match:class blueman-manager, float on

#animations

layerrule = match:class swaync, animation slide right
layerrule = match:class rofi, animation popout
layerrule = match:class wlogout, animation slide down

