$primary = rgb(0284c7)
$surface = rgb(f0faff)
$secondary = rgb(0891b2)
$error = rgb(8a3068)
$tertiary = rgb(0ea5e9)
$surface_lowest = rgb(ebf7fd)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
